### ISSUE TITLE
Example not up to date

### ISSUE THREAD

**Issue by pallix** [drlivingston/kr#3]
The edu.ucdenver.ccp.kr.examples.sesame-remote-kb example is not up to date it uses the :repo keyword for the open method but the actual namespace used in the code for destructuring is :repo-name

**Comment by drlivingston** [comment]
Thanks for noticing this and reporting it, it is appreciated.  The examples have been updated.

I have also extended the examples to show a use of the "visit" api calls, which can allow for going through more results than could otherwise be stored in memory.
